# inference.py
import os
import sys
import logging
import numpy as np
import pandas as pd
import torch
from torch.utils.data import Dataset, DataLoader
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, f1_score
from pathlib import Path
import librosa
import pickle # To load the label encoder
import warnings
warnings.filterwarnings("ignore")

# ---------------------------
# 1. CONFIGURATION (HARDCODED - Match Training Script)
# ---------------------------
PROJECT_ROOT = Path(__file__).resolve().parents[0]  # assuming script is in root
RAW_DIR = PROJECT_ROOT / "data" / "raw" / "messy_mashup"
CHECKPOINT_DIR = PROJECT_ROOT / "checkpoints"
SPLITS_DIR = PROJECT_ROOT / "data" / "processed" / "splits" # Use the splits generated by the script

# Audio params (must match training)
SAMPLE_RATE = 22050
N_MELS = 128
N_FFT = 2048
HOP_LENGTH = 512
FMAX = SAMPLE_RATE // 2
TARGET_FRAMES = 1300
DURATION = TARGET_FRAMES * HOP_LENGTH / SAMPLE_RATE

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Paths
MODEL_PATH = CHECKPOINT_DIR / "best_model.pth"
LABEL_ENCODER_PATH = CHECKPOINT_DIR / "label_encoder.pkl"
TEST_CSV_PATH = SPLITS_DIR / "test.csv" # Use the test split CSV

# Logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)

# ---------------------------
# 2. HELPER FUNCTIONS (from training script)
# ---------------------------
def fix_length(audio, target_len):
    """Pad or truncate audio to target length."""
    if len(audio) < target_len:
        return np.pad(audio, (0, target_len - len(audio)), mode='constant')
    else:
        return audio[:target_len]

def normalise_mel(mel):
    """Min-max normalize mel across time & freq."""
    mel = mel.astype(np.float32)
    mel = (mel - mel.min()) / (mel.max() - mel.min() + 1e-8)
    return mel

def extract_mel(wav_path, sr=SAMPLE_RATE):
    """Extract mel spectrogram from .wav file."""
    y, _ = librosa.load(wav_path, sr=sr, mono=True)
    y = fix_length(y, int(DURATION * sr))
    mel = librosa.feature.melspectrogram(
        y=y,
        sr=sr,
        n_fft=N_FFT,
        hop_length=HOP_LENGTH,
        n_mels=N_MELS,
        fmax=FMAX
    )
    mel = librosa.power_to_db(mel, ref=np.max)
    mel = normalise_mel(mel)
    return mel  # (n_mels, T)

# ---------------------------
# 3. DATASET CLASS (for inference - no augmentation)
# ---------------------------
class InferenceDataset(Dataset):
    def __init__(self, df):
        self.df = df.reset_index(drop=True)

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        row = self.df.iloc[idx]
        mix_path = row["mix_path"] # Assuming the CSV has mix_path column
        label = row["label"] # Assuming the CSV has label column (integer)

        # Load and extract mel
        mel = extract_mel(mix_path)
        mel = torch.from_numpy(mel).float()  # (128, T)

        # Ensure fixed shape
        if mel.shape[1] < TARGET_FRAMES:
            pad = torch.zeros(128, TARGET_FRAMES - mel.shape[1])
            mel = torch.cat([mel, pad], dim=1)
        else:
            mel = mel[:, :TARGET_FRAMES]

        # Return mel, integer label, and the original file_base for identification if needed
        return {"mix": mel.unsqueeze(0), "label": torch.tensor(label, dtype=torch.long), "file_base": row["file_base"]} # (1, 128, T)

# ---------------------------
# 4. LOAD ARTIFACTS
# ---------------------------
logger.info(f"Loading model from {MODEL_PATH}")
logger.info(f"Loading label encoder from {LABEL_ENCODER_PATH}")
logger.info(f"Loading test data from {TEST_CSV_PATH}")

# Load label encoder
with open(LABEL_ENCODER_PATH, "rb") as f:
    le: LabelEncoder = pickle.load(f)
idx2label = {i: l for i, l in enumerate(le.classes_)}
logger.info(f"Loaded label encoder for classes: {list(le.classes_)}")

# Load test dataframe (it should contain 'mix_path' and 'label' columns)
test_df = pd.read_csv(TEST_CSV_PATH)
# The test_df generated by our script has 'genre', 'track_id', 'mix_path', 'file_base', 'label'
logger.info(f"Loaded test dataframe with {len(test_df)} samples.")

# Load model
from fresh_training_from_scratch import GenreClassifier # Import the model class from the training script

num_classes = len(le.classes_)
model = GenreClassifier(num_classes=num_classes).to(DEVICE)

checkpoint = torch.load(MODEL_PATH, map_location=DEVICE, weights_only=False)
model.load_state_dict(checkpoint['model_state_dict'])
model.eval() # Set to eval mode for inference
logger.info("Model loaded and set to eval mode.")

# ---------------------------
# 5. RUN INFERENCE ON TEST SET
# ---------------------------
test_dataset = InferenceDataset(test_df)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False, num_workers=4) # Batch size can be larger for inference

all_preds = []
all_true = []
all_file_bases = [] # Store file bases if needed for debugging

logger.info("Starting inference on test set...")
with torch.no_grad(): # Disable gradient computation for efficiency
    for batch in test_loader:
        x = batch["mix"].to(DEVICE)
        y_true = batch["label"].to(DEVICE)
        file_bases = batch["file_base"] # List of strings

        logits = model(x)
        preds = torch.argmax(logits, dim=1) # Get predicted class indices

        all_preds.extend(preds.cpu().numpy())
        all_true.extend(y_true.cpu().numpy())
        all_file_bases.extend(file_bases) # Extend list of strings

logger.info("Inference completed.")

# ---------------------------
# 6. CALCULATE AND PRINT METRICS
# ---------------------------
# Convert integer labels back to string labels using the label encoder
true_labels_str = le.inverse_transform(all_true)
pred_labels_str = le.inverse_transform(all_preds)

# Calculate overall Macro F1 (for confirmation)
macro_f1 = f1_score(all_true, all_preds, average='macro')
logger.info(f"\n--- Test Set Results ---")
logger.info(f"Overall Macro F1 Score: {macro_f1:.4f}")

# Print detailed classification report
print("\nClassification Report (Test Set):")
print("="*50)
print(classification_report(true_labels_str, pred_labels_str, target_names=le.classes_))
print("="*50)

# Optional: Save the report to a file
report_str = classification_report(true_labels_str, pred_labels_str, target_names=le.classes_)
with open(CHECKPOINT_DIR / "test_classification_report.txt", "w") as f:
    f.write("Classification Report (Test Set):\n")
    f.write("="*50 + "\n")
    f.write(report_str)
    f.write("\n" + "="*50 + "\n")
    f.write(f"\nOverall Macro F1 Score: {macro_f1:.4f}\n")
logger.info(f"Classification report saved to {CHECKPOINT_DIR / 'test_classification_report.txt'}")